#cloud-config

runcmd:
  - mysql -u ${rds_user} --password=${rds_password} -h ${rds_address} < /home/ec2-user/social_something_full/database.sql
  - mysql -u ${rds_user} --password=${rds_password} -h ${rds_address} -e "CREATE USER '${sql_user}'@'10.0.%.%' IDENTIFIED WITH mysql_native_password BY '${sql_password}'; GRANT ALL PRIVILEGES ON ${sql_database}.* TO '${sql_user}'@'10.0.%.%';"
