#cloud-config
write_files:
  - path: /home/ec2-user/social_something_full/app.env
    owner: ec2-user:ec2-user
    permissions: "0644"
    content: |
      BUCKET_NAME='${bucket_name}'
      BUCKET_REGION='${bucket_region}'
      MYSQL_HOST='${sql_host}'
      MYSQL_USER='${sql_user}'
      MYSQL_PASSWORD='${sql_password}'
      MYSQL_DATABASE='${sql_database}'
runcmd:
  - [ systemctl, restart, --no-block, app.service ]
  